# Generated by Django 2.0.6 on 2018-06-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('signal', models.CharField(max_length=200)),
                ('trade', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=200)),
            ],
        ),
    ]
