# Generated by Django 2.0 on 2018-06-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='signal',
            new_name='pnl',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='trade',
        ),
    ]
