# Generated by Django 2.0 on 2018-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180621_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pnl',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='position',
            field=models.CharField(max_length=10000),
        ),
    ]
